### ISSUE TITLE
can't find stats.js

### ISSUE THREAD

**Issue by kesar** [dfvalero/frontendez#1]

**Comment by dfvalero** [comment]
![ec7f0adbbee0d5e8a48d05edc73d3898](https://user-images.githubusercontent.com/337955/105483763-9ccfec80-5caa-11eb-93ea-f736f28831bc.gif)

Feel free to add it! 😂

**Comment by RedBaron80** [comment]
I propose a pair programming session the three of us to rewrite it

**Comment by kesar** [comment]
I just deployed an example here https://bit.ly/2YcoESx
